apiVersion: kubeshare.nthu/v1
kind: SharePod
metadata:
  name: trainnnback211
  annotations:
    "kubeshare/gpu_request": "0.2" # required if allocating GPU
    "kubeshare/gpu_limit": "0.2" # required if allocating GPU
    "kubeshare/gpu_mem": "1610612736" # required if allocating GPU # 1Gi, in bytes
    #"kubeshare/sched_affinity": "red" # optional
    #"kubeshare/sched_anti-affinity": "green" # optional
    #"kubeshare/sched_exclusion": "blue" # optional
spec: # PodSpec
  restartPolicy: Never
  containers:
  - name: trainnnback211
    imagePullPolicy: Never
    image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel
    env:
    #- name: NVIDIA_VISIBLE_DEVICES
    #  value: "all"
    - name: GPU_FRACTION
      value: "GF20"
    - name: MODEL_HUB
      value: "pytorch/vision"
    - name: MODEL_NAME
      value: "resnet50"
    - name: TRAIN_SET
      value: "/workspace/pytorch_datasets/train/"
    - name: VAL_SET
      value: "/workspace/pytorch_datasets/val/"
    - name: TEST_SET
      value: "/workspace/pytorch_datasets/test/"
    - name: BATCH_SIZE
      value: "32"
    - name: TRACE_FOLDER
      value: "/workspace/pytorch_datasets/traces/gpu/"
    - name: EPOCHS
      value: "1"
    - name: LOSS_RATE
      value: "0.001"
    # - name: CUDA_VISIBLE_DEVICES
    #   value: "-1"
    #command: ["nvidia-smi", "-L"]
    command: ["python", "-u" , "/workspace/Talos/pytorch-analyzer/trainmodel/trainNN.py"]
    #command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
    resources:
     limits:
       cpu: "3"
    #    memory: "2Gi"
    volumeMounts:
    - mountPath: /workspace
      name: code-data
  volumes:
  - name: code-data
    hostPath:
      path: /root/github
      type: Directory
