apiVersion: batch/v1
kind: Job
metadata:
  name: trainnnjob
spec: # PodSpec
  template:
    metadata:
      name: train
    spec:
      restartPolicy: Never
      containers:
      - name: demo
        image: pytorch/pytorch:1.8.0-cuda11.1-cudnn8-devel
        env:
        - name: NUM_CLASSES
          value: "2"
        - name: MODEL_NAME
          value: "alexnet"
        - name: TRAIN_SET
          value: "/workspace/pytorch_datasets/train/"
        - name: VAL_SET
          value: "/workspace/pytorch_datasets/val/"
        - name: TEST_SET
          value: "/workspace/pytorch_datasets/test/"
        - name: BATCH_SIZE
          value: "32"
        - name: TRACE_FOLDER
          value: "/workspace/pytorch_datasets/traces/"
        - name: EPOCHS
          value: "1"
        - name: LOSS_RATE
          value: "0.001"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        #command: ["nvidia-smi", "-L"]
        #command: ["python", "/workspace/Talos/pytorch-analyzer/trainmodel/trainNN.py"]
        command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
        resources:
          limits:
            cpu: "1"
            memory: "4Gi"
        volumeMounts:
        - mountPath: /workspace
          name: code-data
      volumes:
      - name: code-data
        hostPath:
          path: /root/github
          type: Directory